import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  const accessToken =
    request.cookies.get("spotify_access_token")?.value;

  if (!accessToken) {
    return NextResponse.json(
      { error: "Not authenticated with Spotify" },
      { status: 401 }
    );
  }

  try {
    const body = await request.json();

    const {
      uris,
      workoutType,
      focus,
      duration,
      genre,
    } = body;

    if (!Array.isArray(uris) || uris.length === 0) {
      return NextResponse.json(
        { error: "No tracks provided" },
        { status: 400 }
      );
    }

    // Step 1: Create an empty private Spotify playlist.
    const createResponse = await fetch(
      "https://api.spotify.com/v1/me/playlists",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: `TempoFit — ${focus}`,
          public: false,
          description:
            `${duration}-minute ${workoutType} workout · ${genre} · Generated by TempoFit`,
        }),
      }
    );

    if (!createResponse.ok) {
      const error = await createResponse.text();

      console.error(
        "Spotify playlist creation failed:",
        createResponse.status,
        error
      );

      return NextResponse.json(
        {
          error: "Failed to create Spotify playlist",
          status: createResponse.status,
        },
        { status: createResponse.status }
      );
    }

    const createdPlaylist = await createResponse.json();

    // Step 2: Add the generated tracks in their existing order.
    const addResponse = await fetch(
      `https://api.spotify.com/v1/playlists/${createdPlaylist.id}/items`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          uris,
        }),
      }
    );

    if (!addResponse.ok) {
      const error = await addResponse.text();

      console.error(
        "Spotify add items failed:",
        addResponse.status,
        error
      );

      return NextResponse.json(
        {
          error: "Playlist created, but tracks could not be added",
          status: addResponse.status,
        },
        { status: addResponse.status }
      );
    }

    return NextResponse.json({
      success: true,
      playlistId: createdPlaylist.id,
      playlistUrl:
        createdPlaylist.external_urls?.spotify ?? null,
      name: createdPlaylist.name,
    });
  } catch (error) {
    console.error("TempoFit Spotify export error:", error);

    return NextResponse.json(
      { error: "Failed to save playlist" },
      { status: 500 }
    );
  }
}